<a href="https://colab.research.google.com/github/DineshKesawamoorthy/nlp/blob/main/Sentence_classification_of_longtext_using_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from transformers import BertForSequenceClassification, BertTokenizer
import torch

# initialize our model and tokenizer
tokenizer = BertTokenizer.from_pretrained('ProsusAI/finbert')
model=BertForSequenceClassification.from_pretrained('ProsusAI/finbert')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/252 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/758 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

In [43]:
long_text="""
Bank funds scam
In the early 70's, banks in India were not allowed to invest in the equity markets. However, they were expected to post profits and to retain a certain ratio (threshold) of their assets in government fixed interest bonds. Mehta squeezed capital out of the banking system to address this requirement of banks and pumped this money into the share market. He promised the banks higher rates of interest, while asking them to transfer the money into his personal account, under the guise of buying securities for them from other banks. At that time, a bank had to go through a broker to buy securities and forward bonds from other banks. Mehta used this money temporarily in his account to buy shares, hike up demand of certain shares (such as that of ACC, Sterlite Industries, and Videocon) dramatically, sell them off, pass on a part of the proceeds to the bank and keep the rest for himself. This resulted in stocks like ACC, which was trading in 1991 for ₹200/share, catapult to nearly ₹9,000 in just 3 months.[6]

Bank receipt scam
Another major instrument was the bank receipt (BR). In a ready forward deal, securities were not moved back and forth in actuality. Instead, the borrower, i.e. the seller of securities, gave the buyer of the securities a BR. The BR serves as a receipt from the selling bank, and also promises that the buyer will receive the securities they have paid for at the end of the term. Having figured this out, Mehta needed banks, which could issue fake BRs, or BRs not backed by any government securities.

Once these fake BRs were issued, they were passed on to other banks and the banks in turn gave money to Mehta, plainly assuming that they were lending against government securities when this was not really the case.[7] He took the price of ACC from ₹200 to ₹9,000. That was an increase of 4,400%. Since he had to book profits in the end, the day he sold was the day when the markets crashed.[8][9]

Ready forward deal scam
The ready forward deal is a way where a single broker liaisons between two banks. When one bank wants to sell securities, it approaches the broker. This broker goes to another bank and tries to sell the securities and vice versa for buying. Since Mehta was a renowned broker, he got cheques issued in his name instead of the bank. When the bank wanted money for the securities, he approached another bank and repeated the same process, and invested the bank money in the stock market.[10] Mehta used the ready forward deal and applied it to the Bank Receipts system of the Indian financial systems. This system was the most flawed system as the Janakiraman Committee restructured the entire Bank Receipts system after the 1992 scam."""

In [44]:
tokens=tokenizer.encode_plus(long_text,add_special_tokens=False,return_tensors='pt')
print('BERT acceptable token length is 512')
print(len(tokens['input_ids'][0]))
tokens

BERT acceptable token length is 512
589


{'input_ids': tensor([[ 2924,  5029,  8040,  3286,  1999,  1996,  2220,  3963,  1005,  1055,
          1010,  5085,  1999,  2634,  2020,  2025,  3039,  2000, 15697,  1999,
          1996, 10067,  6089,  1012,  2174,  1010,  2027,  2020,  3517,  2000,
          2695, 11372,  1998,  2000,  9279,  1037,  3056,  6463,  1006, 11207,
          1007,  1997,  2037,  7045,  1999,  2231,  4964,  3037,  9547,  1012,
          2033, 22893,  7757,  3007,  2041,  1997,  1996,  8169,  2291,  2000,
          4769,  2023,  9095,  1997,  5085,  1998, 16486,  2023,  2769,  2046,
          1996,  3745,  3006,  1012,  2002,  5763,  1996,  5085,  3020,  6165,
          1997,  3037,  1010,  2096,  4851,  2068,  2000,  4651,  1996,  2769,
          2046,  2010,  3167,  4070,  1010,  2104,  1996, 21980,  1997,  9343,
         12012,  2005,  2068,  2013,  2060,  5085,  1012,  2012,  2008,  2051,
          1010,  1037,  2924,  2018,  2000,  2175,  2083,  1037, 20138,  2000,
          4965, 12012,  1998,  2830,  

In [45]:
a=torch.arange(10)
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
torch.split(a,4)

(tensor([0, 1, 2, 3]), tensor([4, 5, 6, 7]), tensor([8, 9]))

In [47]:
input_id_chuncks=tokens['input_ids'][0].split(510)
mask_chunks=tokens['attention_mask'][0].split(510)

In [11]:
len(input_id_chuncks[1])

136

In [12]:
a=torch.cat([torch.Tensor([101]),a,torch.Tensor([102])])
a

tensor([101.,   0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9., 102.])

In [13]:
padding_len=20- a.shape[0]
padding_len

8

In [14]:
if padding_len > 0:
  a=torch.cat([a,torch.Tensor([0]*padding_len)])
a

tensor([101.,   0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9., 102.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.])

In [48]:
chunk_size=512

input_id_chunks = list(tokens['input_ids'][0].split(chunk_size -2)) # split function returns the tuple so we convert into list
mask_chunks=list(tokens['attention_mask'][0].split(chunk_size -2))
#print(mask_chunks[0])

for i in range(len(input_id_chunks)):
  input_id_chunks[i]=torch.cat([torch.Tensor([101]),input_id_chunks[i],torch.Tensor([102])])
  mask_chunks[i]=torch.cat([torch.Tensor([1]),mask_chunks[i],torch.Tensor([1])])

  padding_len=chunk_size - input_id_chunks[i].shape[0]

  if padding_len > 0:
    input_id_chunks[i]=torch.cat([input_id_chunks[i],torch.Tensor([0]*padding_len)])
    mask_chunks[i]=torch.cat([mask_chunks[i],torch.Tensor([0]*padding_len)])





In [49]:
for chunk in input_id_chunks:
  print(len(chunk))

512
512


In [27]:
chunk

tensor([  101.,  8342.,  2041.,  1012.,  2009.,  2419.,  1996.,  4614.,  2000.,
        28667.,  5644., 18688.,  4493.,  3361.,  3001.,  1998.,  2717.,  6820.,
        14890.,  2009.,  1012.,  1996.,  2034.,  8332.,  2689.,  2001.,  2000.,
         2501., 10504.,  2081.,  2005., 13131., 10518.,  1999., 28348.,  2924.,
        28258.,  1998.,  7506.,  2236., 27106.,  2015.,  2000.,  4652., 27105.,
        11817.,  1012.,  2006.,  1996.,  6040.,  1997.,  1996., 23341., 23630.,
        23093.,  2837.,  1010.,  1037.,  2837.,  2001.,  2511.,  2000., 17467.,
         1996., 12012.,  1998.,  3863.,  2604.,  1997.,  2634.,  1012.,  1996.,
         3078., 12832.,  1997.,  1996.,  2837.,  2001.,  2000.,  5787.,  3201.,
         2830.,  1998.,  3313.,  3201.,  2830.,  9144.,  2000.,  2231., 12012.,
         2069.,  1012.,  2035.,  5085.,  2020.,  2081., 12731., 16033., 11692.,
         2015.,  2738.,  2084., 27928.,  1999., 11817.,  1012.,  5085.,  2020.,
         2000.,  2031.,  1037.,  3584., 

In [51]:
input_ids=torch.stack(input_id_chunks)
attention_mask=torch.stack(mask_chunks)

In [52]:
input_dict={
    'input_ids':input_ids.long(),
    'attention_mask':attention_mask.int()
}
input_dict

{'input_ids': tensor([[ 101, 2924, 5029,  ..., 2924, 1012,  102],
         [ 101, 2043, 1996,  ...,    0,    0,    0]]),
 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1],
         [1, 1, 1,  ..., 0, 0, 0]], dtype=torch.int32)}

In [53]:
output=model(**input_dict)
probs=torch.nn.functional.softmax(output[0],dim=-1)
probs=probs.mean(dim=0)

In [54]:
probs

tensor([0.0441, 0.0930, 0.8629], grad_fn=<MeanBackward1>)

In [55]:
torch.argmax(probs)

tensor(2)