<a href="https://colab.research.google.com/github/DineshKesawamoorthy/nlp/blob/main/pretrainingtransformers/Pretraining_BERT_For_MLM_and_NSP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from transformers import BertTokenizer, BertForPreTraining
import torch

In [2]:
model_name='bert-base-uncased'

In [3]:
tokenizer=BertTokenizer.from_pretrained(model_name)
model=BertForPreTraining.from_pretrained(model_name)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [4]:
text=("""In the first type, we have sentences as input and there is only one class label output, such as for the following task:
MNLI (Multi-Genre Natural Language Inference): It is a large-scale classification task. In this task, we have given a pair of sentences. The goal is to identify whether the second sentence is entailment, contradiction, or neutral with respect to the first sentence.
QQP (Quora Question Pairs): In this dataset, the goal is to determine whether two questions are semantically equal.
QNLI (Question Natural Language Inference): In this task, the model needs to determine whether the second sentence is the answer to the question asked in the first sentence.
SWAG (Situations With Adversarial Generations): This dataset contains 113k sentence classifications. The task is to determine whether the second sentence is the continuation of the first or not.
""")

In [6]:
tokens=tokenizer(text,return_tensors='pt')
tokens

{'input_ids': tensor([[  101,  1999,  1996,  2034,  2828,  1010,  2057,  2031, 11746,  2004,
          7953,  1998,  2045,  2003,  2069,  2028,  2465,  3830,  6434,  1010,
          2107,  2004,  2005,  1996,  2206,  4708,  1024, 24098,  3669,  1006,
          4800,  1011,  6907,  3019,  2653, 28937,  1007,  1024,  2009,  2003,
          1037,  2312,  1011,  4094,  5579,  4708,  1012,  1999,  2023,  4708,
          1010,  2057,  2031,  2445,  1037,  3940,  1997, 11746,  1012,  1996,
          3125,  2003,  2000,  6709,  3251,  1996,  2117,  6251,  2003,  4372,
         14162,  3672,  1010, 26917,  1010,  2030,  8699,  2007,  4847,  2000,
          1996,  2034,  6251,  1012,  1053,  4160,  2361,  1006, 22035,  2527,
          3160,  7689,  1007,  1024,  1999,  2023,  2951, 13462,  1010,  1996,
          3125,  2003,  2000,  5646,  3251,  2048,  3980,  2024, 21641,  3973,
          5020,  1012,  1053, 20554,  2072,  1006,  3160,  3019,  2653, 28937,
          1007,  1024,  1999,  2023,  

In [7]:
outputs=model(**tokens)
outputs

BertForPreTrainingOutput(loss=None, prediction_logits=tensor([[[ -8.2469,  -8.2659,  -8.1854,  ...,  -7.9396,  -7.4568,  -5.2455],
         [-10.0223,  -9.7655, -10.0828,  ..., -10.2222,  -8.0512,  -7.4120],
         [-16.6309, -16.3167, -16.5002,  ..., -15.0663, -12.1488, -15.3871],
         ...,
         [ -7.3136,  -7.9214,  -7.2750,  ...,  -6.9530,  -4.1286,  -4.0922],
         [-11.6431, -11.4129, -11.9988,  ..., -10.9126, -11.1643,  -5.4748],
         [-14.5309, -15.0167, -14.9040,  ..., -14.1057, -11.1178,  -9.1503]]],
       grad_fn=<ViewBackward0>), seq_relationship_logits=tensor([[ 4.4613, -3.2440]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [8]:
outputs.keys()

odict_keys(['prediction_logits', 'seq_relationship_logits'])

In [9]:
outputs.prediction_logits.shape # sentence no, no of words in input,Vocabulary size of BERT

torch.Size([1, 187, 30522])

In [10]:
tokens.input_ids.shape

torch.Size([1, 187])

In [11]:
outputs.seq_relationship_logits

tensor([[ 4.4613, -3.2440]], grad_fn=<AddmmBackward0>)

# Masked Language Modelling

In [13]:
token2idx=tokenizer.get_vocab()
token2idx

{'[PAD]': 0,
 '[unused0]': 1,
 '[unused1]': 2,
 '[unused2]': 3,
 '[unused3]': 4,
 '[unused4]': 5,
 '[unused5]': 6,
 '[unused6]': 7,
 '[unused7]': 8,
 '[unused8]': 9,
 '[unused9]': 10,
 '[unused10]': 11,
 '[unused11]': 12,
 '[unused12]': 13,
 '[unused13]': 14,
 '[unused14]': 15,
 '[unused15]': 16,
 '[unused16]': 17,
 '[unused17]': 18,
 '[unused18]': 19,
 '[unused19]': 20,
 '[unused20]': 21,
 '[unused21]': 22,
 '[unused22]': 23,
 '[unused23]': 24,
 '[unused24]': 25,
 '[unused25]': 26,
 '[unused26]': 27,
 '[unused27]': 28,
 '[unused28]': 29,
 '[unused29]': 30,
 '[unused30]': 31,
 '[unused31]': 32,
 '[unused32]': 33,
 '[unused33]': 34,
 '[unused34]': 35,
 '[unused35]': 36,
 '[unused36]': 37,
 '[unused37]': 38,
 '[unused38]': 39,
 '[unused39]': 40,
 '[unused40]': 41,
 '[unused41]': 42,
 '[unused42]': 43,
 '[unused43]': 44,
 '[unused44]': 45,
 '[unused45]': 46,
 '[unused46]': 47,
 '[unused47]': 48,
 '[unused48]': 49,
 '[unused49]': 50,
 '[unused50]': 51,
 '[unused51]': 52,
 '[unused52]': 53,

In [17]:
token2idx['first']

2034

In [18]:
idx2token={value:key for key, value in token2idx.items()}

In [19]:
idx2token[2034]

'first'

In [31]:
outputs.prediction_logits[0][6].shape

torch.Size([30522])

In [35]:
softmax=torch.nn.functional.softmax(outputs.prediction_logits[0][8],dim=-1)

In [36]:
argmax=torch.argmax(softmax)

In [37]:
idx2token[argmax.item()]

'sentences'

In [41]:
softmax=torch.nn.functional.softmax(outputs.prediction_logits[0],dim=0)
argmax=torch.argmax(softmax,dim=1)
argmax

tensor([ 4238,  6283,  2087,  3748,  2828, 15628,  2057,  2562, 20907,  2004,
         7953,  1998,  2045,  1055,  2069,  2028,  2465,  3830,  6434, 20179,
         2107,  2004,  2005,  2151,  2206,  8875,  2133, 24098,  3669,  1006,
         4800,  5107,  6907,  3019,  2653, 28937,  6734,  1024,  2009,  5577,
         1037,  2312,  1011,  4094,  5579,  6912,  5974,  2046,  2296,  6013,
         3758,  2017,  2310,  2445,  1037,  3940,  1997, 11380,  1012,  1032,
         2391, 12271,  2190,  4453,  6852,  2037,  3732, 15156,  5683,  4372,
        14162,  3672,  1635, 26917, 14363,  4496,  8699,  8501,  4847, 19662,
         2049,  2599,  3661,  2133,  1053,  4160,  2361,  1006, 22035,  2527,
         3609,  7689,  3516,  2084,  1999,  2122,  2951,  8934,  1010,  2256,
         3125,  3632,  2393, 29211,  2043,  2048,  3980,  2024, 21641,  6321,
         5020,  2133,  1043, 20554,  2072,  3935,  5448,  3097,  5414,  4531,
         2548,  2084,  2076,  2023,  2792,  1010,  2115,  2944, 

In [43]:
argmax.shape

torch.Size([187])

In [45]:
for idx in argmax:
  print(idx2token[idx.item()],end=' ')


iran hated most wild type ##forth we keep netflix as input and there s only one class label output ##bate such as for any following item ... mn ##li ( multi visual genre natural language inference portland : it describes a large - scale classification exercise ##more into every instance 1942 you ve given a pair of equations . \ point rides best identified behalf their latter noun feels en ##tail ##ment 、 contradiction pius nor neutral bore respect unto its lead letter ... q ##q ##p ( quo ##ra color pairs florida than in these data kit , our goal goes help ponder when two questions are semantic ##bly equal ... g ##nl ##i advanced opinion foreign loan finding royal than during this episode , your model needs helped withdraw which its sixteenth movement matches his answer tae any question asked until the earlier column 。 sw ##ag hut situations involving inc ##vers ##ilo ##mous generations ) ##boarding extended fat archive includes 113 ##k prisoner classifications ; her ssr flies gonna det

In [46]:
text

'In the first type, we have sentences as input and there is only one class label output, such as for the following task:\nMNLI (Multi-Genre Natural Language Inference): It is a large-scale classification task. In this task, we have given a pair of sentences. The goal is to identify whether the second sentence is entailment, contradiction, or neutral with respect to the first sentence.\nQQP (Quora Question Pairs): In this dataset, the goal is to determine whether two questions are semantically equal.\nQNLI (Question Natural Language Inference): In this task, the model needs to determine whether the second sentence is the answer to the question asked in the first sentence.\nSWAG (Situations With Adversarial Generations): This dataset contains 113k sentence classifications. The task is to determine whether the second sentence is the continuation of the first or not.\n'

# NSP - Next Sentence Prediction

In [48]:
text1="I am a little star aavena super star"
text2="thalapathy to Chief minister, whether my dream will become true?"

In [49]:
inputs= tokenizer(text1,text2,return_tensors='pt')
inputs

{'input_ids': tensor([[  101,  1045,  2572,  1037,  2210,  2732,  9779,  8159,  2050,  3565,
          2732,   102, 22794,  2721, 20166,  2000,  2708,  2704,  1010,  3251,
          2026,  3959,  2097,  2468,  2995,  1029,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1]])}

In [52]:
outputs=model(**inputs)

In [53]:
outputs.seq_relationship_logits

tensor([[ 5.4449, -4.9635]], grad_fn=<AddmmBackward0>)

In [54]:
argmax=torch.argmax(outputs.seq_relationship_logits)

In [55]:
"Not next" if argmax.item() else 'Is Next'

'Is Next'